// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feg/protos/radius_proxy.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AaaRequest struct {
	SubscriberId         string   `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Packet               []byte   `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AaaRequest) Reset()         { *m = AaaRequest{} }
func (m *AaaRequest) String() string { return proto.CompactTextString(m) }
func (*AaaRequest) ProtoMessage()    {}
func (*AaaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fe03f7feabca2a3, []int{0}
}

func (m *AaaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AaaRequest.Unmarshal(m, b)
}
func (m *AaaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AaaRequest.Marshal(b, m, deterministic)
}
func (m *AaaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AaaRequest.Merge(m, src)
}
func (m *AaaRequest) XXX_Size() int {
	return xxx_messageInfo_AaaRequest.Size(m)
}
func (m *AaaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AaaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AaaRequest proto.InternalMessageInfo

func (m *AaaRequest) GetSubscriberId() string {
	if m != nil {
		return m.SubscriberId
	}
	return ""
}

func (m *AaaRequest) GetPacket() []byte {
	if m != nil {
		return m.Packet
	}
	return nil
}

type AaaResponse struct {
	Packet               []byte   `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AaaResponse) Reset()         { *m = AaaResponse{} }
func (m *AaaResponse) String() string { return proto.CompactTextString(m) }
func (*AaaResponse) ProtoMessage()    {}
func (*AaaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fe03f7feabca2a3, []int{1}
}

func (m *AaaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AaaResponse.Unmarshal(m, b)
}
func (m *AaaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AaaResponse.Marshal(b, m, deterministic)
}
func (m *AaaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AaaResponse.Merge(m, src)
}
func (m *AaaResponse) XXX_Size() int {
	return xxx_messageInfo_AaaResponse.Size(m)
}
func (m *AaaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AaaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AaaResponse proto.InternalMessageInfo

func (m *AaaResponse) GetPacket() []byte {
	if m != nil {
		return m.Packet
	}
	return nil
}

func init() {
	proto.RegisterType((*AaaRequest)(nil), "magma.feg.aaa_request")
	proto.RegisterType((*AaaResponse)(nil), "magma.feg.aaa_response")
}

func init() { proto.RegisterFile("feg/protos/radius_proxy.proto", fileDescriptor_2fe03f7feabca2a3) }

var fileDescriptor_2fe03f7feabca2a3 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x4b, 0x4d, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x2f, 0x4a, 0x4c, 0xc9, 0x2c, 0x2d, 0x8e, 0x2f, 0x28,
	0xca, 0xaf, 0xa8, 0xd4, 0x03, 0x8b, 0x09, 0x71, 0xe6, 0x26, 0xa6, 0xe7, 0x26, 0xea, 0xa5, 0xa5,
	0xa6, 0x2b, 0x79, 0x71, 0x71, 0x27, 0x26, 0x26, 0xc6, 0x17, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0x29, 0x73, 0xf1, 0x16, 0x97, 0x26, 0x15, 0x27, 0x17, 0x65, 0x26, 0xa5, 0x16, 0xc5, 0x67,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xf1, 0x20, 0x04, 0x3d, 0x53, 0x84, 0xc4, 0xb8,
	0xd8, 0x0a, 0x12, 0x93, 0xb3, 0x53, 0x4b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xa0, 0x3c,
	0x25, 0x35, 0x2e, 0x1e, 0x88, 0x59, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x48, 0xea, 0x18, 0x91,
	0xd5, 0x19, 0xf9, 0x73, 0x71, 0x07, 0x81, 0x1d, 0x15, 0x00, 0x72, 0x93, 0x90, 0x03, 0x17, 0x37,
	0x98, 0x11, 0x00, 0x96, 0x15, 0x12, 0xd3, 0x83, 0xbb, 0x4e, 0x0f, 0xc9, 0x69, 0x52, 0xe2, 0x18,
	0xe2, 0x10, 0x6b, 0x94, 0x18, 0x9c, 0xa4, 0xa3, 0x24, 0xc1, 0x72, 0xfa, 0x20, 0x6f, 0x27, 0xe7,
	0xe4, 0x97, 0xa6, 0xe8, 0xa7, 0xe7, 0x43, 0xfd, 0x9f, 0xc4, 0x06, 0xa6, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x10, 0xf5, 0x84, 0x55, 0x14, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RadiusProxyClient is the client API for RadiusProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RadiusProxyClient interface {
	ProxyPacket(ctx context.Context, in *AaaRequest, opts ...grpc.CallOption) (*AaaResponse, error)
}

type radiusProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewRadiusProxyClient(cc grpc.ClientConnInterface) RadiusProxyClient {
	return &radiusProxyClient{cc}
}

func (c *radiusProxyClient) ProxyPacket(ctx context.Context, in *AaaRequest, opts ...grpc.CallOption) (*AaaResponse, error) {
	out := new(AaaResponse)
	err := c.cc.Invoke(ctx, "/magma.feg.RadiusProxy/ProxyPacket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadiusProxyServer is the server API for RadiusProxy service.
type RadiusProxyServer interface {
	ProxyPacket(context.Context, *AaaRequest) (*AaaResponse, error)
}

// UnimplementedRadiusProxyServer can be embedded to have forward compatible implementations.
type UnimplementedRadiusProxyServer struct {
}

func (*UnimplementedRadiusProxyServer) ProxyPacket(ctx context.Context, req *AaaRequest) (*AaaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyPacket not implemented")
}

func RegisterRadiusProxyServer(s *grpc.Server, srv RadiusProxyServer) {
	s.RegisterService(&_RadiusProxy_serviceDesc, srv)
}

func _RadiusProxy_ProxyPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AaaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadiusProxyServer).ProxyPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.feg.RadiusProxy/ProxyPacket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadiusProxyServer).ProxyPacket(ctx, req.(*AaaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RadiusProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.feg.RadiusProxy",
	HandlerType: (*RadiusProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProxyPacket",
			Handler:    _RadiusProxy_ProxyPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feg/protos/radius_proxy.proto",
}
