// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feg/protos/mconfig/mconfigs.proto

package mconfig // import "magma/feg/cloud/go/protos/mconfig"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protos "magma/orc8r/lib/go/protos"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GyInitMethod int32

const (
	GyInitMethod_RESERVED    GyInitMethod = 0
	GyInitMethod_PER_SESSION GyInitMethod = 1
	GyInitMethod_PER_KEY     GyInitMethod = 2
)

var GyInitMethod_name = map[int32]string{
	0: "RESERVED",
	1: "PER_SESSION",
	2: "PER_KEY",
}
var GyInitMethod_value = map[string]int32{
	"RESERVED":    0,
	"PER_SESSION": 1,
	"PER_KEY":     2,
}

func (x GyInitMethod) String() string {
	return proto.EnumName(GyInitMethod_name, int32(x))
}
func (GyInitMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{0}
}

// ------------------------------------------------------------------------------
// FeG configs
// ------------------------------------------------------------------------------
type DiamClientConfig struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Retransmits          uint32   `protobuf:"varint,3,opt,name=retransmits,proto3" json:"retransmits,omitempty"`
	WatchdogInterval     uint32   `protobuf:"varint,4,opt,name=watchdog_interval,json=watchdogInterval,proto3" json:"watchdog_interval,omitempty"`
	RetryCount           uint32   `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	LocalAddress         string   `protobuf:"bytes,6,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	ProductName          string   `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Realm                string   `protobuf:"bytes,8,opt,name=realm,proto3" json:"realm,omitempty"`
	Host                 string   `protobuf:"bytes,9,opt,name=host,proto3" json:"host,omitempty"`
	DestRealm            string   `protobuf:"bytes,10,opt,name=dest_realm,json=destRealm,proto3" json:"dest_realm,omitempty"`
	DestHost             string   `protobuf:"bytes,11,opt,name=dest_host,json=destHost,proto3" json:"dest_host,omitempty"`
	DisableDestHost      bool     `protobuf:"varint,12,opt,name=disable_dest_host,json=disableDestHost,proto3" json:"disable_dest_host,omitempty"`
	OverwriteDestHost    bool     `protobuf:"varint,13,opt,name=overwrite_dest_host,json=overwriteDestHost,proto3" json:"overwrite_dest_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamClientConfig) Reset()         { *m = DiamClientConfig{} }
func (m *DiamClientConfig) String() string { return proto.CompactTextString(m) }
func (*DiamClientConfig) ProtoMessage()    {}
func (*DiamClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{0}
}
func (m *DiamClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamClientConfig.Unmarshal(m, b)
}
func (m *DiamClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamClientConfig.Marshal(b, m, deterministic)
}
func (dst *DiamClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamClientConfig.Merge(dst, src)
}
func (m *DiamClientConfig) XXX_Size() int {
	return xxx_messageInfo_DiamClientConfig.Size(m)
}
func (m *DiamClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DiamClientConfig proto.InternalMessageInfo

func (m *DiamClientConfig) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *DiamClientConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DiamClientConfig) GetRetransmits() uint32 {
	if m != nil {
		return m.Retransmits
	}
	return 0
}

func (m *DiamClientConfig) GetWatchdogInterval() uint32 {
	if m != nil {
		return m.WatchdogInterval
	}
	return 0
}

func (m *DiamClientConfig) GetRetryCount() uint32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *DiamClientConfig) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *DiamClientConfig) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *DiamClientConfig) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

func (m *DiamClientConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DiamClientConfig) GetDestRealm() string {
	if m != nil {
		return m.DestRealm
	}
	return ""
}

func (m *DiamClientConfig) GetDestHost() string {
	if m != nil {
		return m.DestHost
	}
	return ""
}

func (m *DiamClientConfig) GetDisableDestHost() bool {
	if m != nil {
		return m.DisableDestHost
	}
	return false
}

func (m *DiamClientConfig) GetOverwriteDestHost() bool {
	if m != nil {
		return m.OverwriteDestHost
	}
	return false
}

type DiamServerConfig struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LocalAddress         string   `protobuf:"bytes,3,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	DestHost             string   `protobuf:"bytes,4,opt,name=dest_host,json=destHost,proto3" json:"dest_host,omitempty"`
	DestRealm            string   `protobuf:"bytes,5,opt,name=dest_realm,json=destRealm,proto3" json:"dest_realm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamServerConfig) Reset()         { *m = DiamServerConfig{} }
func (m *DiamServerConfig) String() string { return proto.CompactTextString(m) }
func (*DiamServerConfig) ProtoMessage()    {}
func (*DiamServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{1}
}
func (m *DiamServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamServerConfig.Unmarshal(m, b)
}
func (m *DiamServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamServerConfig.Marshal(b, m, deterministic)
}
func (dst *DiamServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamServerConfig.Merge(dst, src)
}
func (m *DiamServerConfig) XXX_Size() int {
	return xxx_messageInfo_DiamServerConfig.Size(m)
}
func (m *DiamServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DiamServerConfig proto.InternalMessageInfo

func (m *DiamServerConfig) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *DiamServerConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DiamServerConfig) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *DiamServerConfig) GetDestHost() string {
	if m != nil {
		return m.DestHost
	}
	return ""
}

func (m *DiamServerConfig) GetDestRealm() string {
	if m != nil {
		return m.DestRealm
	}
	return ""
}

type S6AConfig struct {
	LogLevel protos.LogLevel   `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	Server   *DiamClientConfig `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	// Percentage of request failures considered to be unhealthy
	RequestFailureThreshold float32 `protobuf:"fixed32,6,opt,name=request_failure_threshold,json=requestFailureThreshold,proto3" json:"request_failure_threshold,omitempty"`
	// Minimum number of requests necessary to consider a metrics snapshot valid
	MinimumRequestThreshold uint32   `protobuf:"varint,7,opt,name=minimum_request_threshold,json=minimumRequestThreshold,proto3" json:"minimum_request_threshold,omitempty"`
	PlmnIds                 []string `protobuf:"bytes,8,rep,name=PlmnIds,proto3" json:"PlmnIds,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *S6AConfig) Reset()         { *m = S6AConfig{} }
func (m *S6AConfig) String() string { return proto.CompactTextString(m) }
func (*S6AConfig) ProtoMessage()    {}
func (*S6AConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{2}
}
func (m *S6AConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S6AConfig.Unmarshal(m, b)
}
func (m *S6AConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S6AConfig.Marshal(b, m, deterministic)
}
func (dst *S6AConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S6AConfig.Merge(dst, src)
}
func (m *S6AConfig) XXX_Size() int {
	return xxx_messageInfo_S6AConfig.Size(m)
}
func (m *S6AConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_S6AConfig.DiscardUnknown(m)
}

var xxx_messageInfo_S6AConfig proto.InternalMessageInfo

func (m *S6AConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *S6AConfig) GetServer() *DiamClientConfig {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *S6AConfig) GetRequestFailureThreshold() float32 {
	if m != nil {
		return m.RequestFailureThreshold
	}
	return 0
}

func (m *S6AConfig) GetMinimumRequestThreshold() uint32 {
	if m != nil {
		return m.MinimumRequestThreshold
	}
	return 0
}

func (m *S6AConfig) GetPlmnIds() []string {
	if m != nil {
		return m.PlmnIds
	}
	return nil
}

type VirtualApnRule struct {
	// apn_filter is a Regex to match APN values
	ApnFilter string `protobuf:"bytes,1,opt,name=apn_filter,json=apnFilter,proto3" json:"apn_filter,omitempty"`
	// apn_overwrite is the new APN to overwrite with when filters match
	ApnOverwrite string `protobuf:"bytes,2,opt,name=apn_overwrite,json=apnOverwrite,proto3" json:"apn_overwrite,omitempty"`
	// charging_characteristics_filter is a Regex to match
	// ChargingCharacteristics values
	ChargingCharacteristicsFilter string   `protobuf:"bytes,3,opt,name=charging_characteristics_filter,json=chargingCharacteristicsFilter,proto3" json:"charging_characteristics_filter,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *VirtualApnRule) Reset()         { *m = VirtualApnRule{} }
func (m *VirtualApnRule) String() string { return proto.CompactTextString(m) }
func (*VirtualApnRule) ProtoMessage()    {}
func (*VirtualApnRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{3}
}
func (m *VirtualApnRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualApnRule.Unmarshal(m, b)
}
func (m *VirtualApnRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualApnRule.Marshal(b, m, deterministic)
}
func (dst *VirtualApnRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualApnRule.Merge(dst, src)
}
func (m *VirtualApnRule) XXX_Size() int {
	return xxx_messageInfo_VirtualApnRule.Size(m)
}
func (m *VirtualApnRule) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualApnRule.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualApnRule proto.InternalMessageInfo

func (m *VirtualApnRule) GetApnFilter() string {
	if m != nil {
		return m.ApnFilter
	}
	return ""
}

func (m *VirtualApnRule) GetApnOverwrite() string {
	if m != nil {
		return m.ApnOverwrite
	}
	return ""
}

func (m *VirtualApnRule) GetChargingCharacteristicsFilter() string {
	if m != nil {
		return m.ChargingCharacteristicsFilter
	}
	return ""
}

type GxConfig struct {
	Server               *DiamClientConfig   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	OverwriteApn         string              `protobuf:"bytes,2,opt,name=OverwriteApn,proto3" json:"OverwriteApn,omitempty"`
	Servers              []*DiamClientConfig `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	DisableGx            bool                `protobuf:"varint,4,opt,name=DisableGx,proto3" json:"DisableGx,omitempty"`
	VirtualApnRules      []*VirtualApnRule   `protobuf:"bytes,5,rep,name=virtual_apn_rules,json=virtualApnRules,proto3" json:"virtual_apn_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GxConfig) Reset()         { *m = GxConfig{} }
func (m *GxConfig) String() string { return proto.CompactTextString(m) }
func (*GxConfig) ProtoMessage()    {}
func (*GxConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{4}
}
func (m *GxConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GxConfig.Unmarshal(m, b)
}
func (m *GxConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GxConfig.Marshal(b, m, deterministic)
}
func (dst *GxConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GxConfig.Merge(dst, src)
}
func (m *GxConfig) XXX_Size() int {
	return xxx_messageInfo_GxConfig.Size(m)
}
func (m *GxConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GxConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GxConfig proto.InternalMessageInfo

func (m *GxConfig) GetServer() *DiamClientConfig {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *GxConfig) GetOverwriteApn() string {
	if m != nil {
		return m.OverwriteApn
	}
	return ""
}

func (m *GxConfig) GetServers() []*DiamClientConfig {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *GxConfig) GetDisableGx() bool {
	if m != nil {
		return m.DisableGx
	}
	return false
}

func (m *GxConfig) GetVirtualApnRules() []*VirtualApnRule {
	if m != nil {
		return m.VirtualApnRules
	}
	return nil
}

type GyConfig struct {
	Server               *DiamClientConfig   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	InitMethod           GyInitMethod        `protobuf:"varint,2,opt,name=init_method,json=initMethod,proto3,enum=magma.mconfig.GyInitMethod" json:"init_method,omitempty"`
	OverwriteApn         string              `protobuf:"bytes,3,opt,name=OverwriteApn,proto3" json:"OverwriteApn,omitempty"`
	Servers              []*DiamClientConfig `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	DisableGy            bool                `protobuf:"varint,5,opt,name=DisableGy,proto3" json:"DisableGy,omitempty"`
	VirtualApnRules      []*VirtualApnRule   `protobuf:"bytes,6,rep,name=virtual_apn_rules,json=virtualApnRules,proto3" json:"virtual_apn_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GyConfig) Reset()         { *m = GyConfig{} }
func (m *GyConfig) String() string { return proto.CompactTextString(m) }
func (*GyConfig) ProtoMessage()    {}
func (*GyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{5}
}
func (m *GyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GyConfig.Unmarshal(m, b)
}
func (m *GyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GyConfig.Marshal(b, m, deterministic)
}
func (dst *GyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GyConfig.Merge(dst, src)
}
func (m *GyConfig) XXX_Size() int {
	return xxx_messageInfo_GyConfig.Size(m)
}
func (m *GyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GyConfig proto.InternalMessageInfo

func (m *GyConfig) GetServer() *DiamClientConfig {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *GyConfig) GetInitMethod() GyInitMethod {
	if m != nil {
		return m.InitMethod
	}
	return GyInitMethod_RESERVED
}

func (m *GyConfig) GetOverwriteApn() string {
	if m != nil {
		return m.OverwriteApn
	}
	return ""
}

func (m *GyConfig) GetServers() []*DiamClientConfig {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *GyConfig) GetDisableGy() bool {
	if m != nil {
		return m.DisableGy
	}
	return false
}

func (m *GyConfig) GetVirtualApnRules() []*VirtualApnRule {
	if m != nil {
		return m.VirtualApnRules
	}
	return nil
}

type SessionProxyConfig struct {
	LogLevel protos.LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	Gx       *GxConfig       `protobuf:"bytes,5,opt,name=gx,proto3" json:"gx,omitempty"`
	Gy       *GyConfig       `protobuf:"bytes,6,opt,name=gy,proto3" json:"gy,omitempty"`
	// Percentage of request failures considered to be unhealthy
	RequestFailureThreshold float32 `protobuf:"fixed32,7,opt,name=request_failure_threshold,json=requestFailureThreshold,proto3" json:"request_failure_threshold,omitempty"`
	// Minimum number of requests necessary to consider a metrics snapshot valid
	MinimumRequestThreshold uint32   `protobuf:"varint,8,opt,name=minimum_request_threshold,json=minimumRequestThreshold,proto3" json:"minimum_request_threshold,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SessionProxyConfig) Reset()         { *m = SessionProxyConfig{} }
func (m *SessionProxyConfig) String() string { return proto.CompactTextString(m) }
func (*SessionProxyConfig) ProtoMessage()    {}
func (*SessionProxyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{6}
}
func (m *SessionProxyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionProxyConfig.Unmarshal(m, b)
}
func (m *SessionProxyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionProxyConfig.Marshal(b, m, deterministic)
}
func (dst *SessionProxyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionProxyConfig.Merge(dst, src)
}
func (m *SessionProxyConfig) XXX_Size() int {
	return xxx_messageInfo_SessionProxyConfig.Size(m)
}
func (m *SessionProxyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionProxyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SessionProxyConfig proto.InternalMessageInfo

func (m *SessionProxyConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *SessionProxyConfig) GetGx() *GxConfig {
	if m != nil {
		return m.Gx
	}
	return nil
}

func (m *SessionProxyConfig) GetGy() *GyConfig {
	if m != nil {
		return m.Gy
	}
	return nil
}

func (m *SessionProxyConfig) GetRequestFailureThreshold() float32 {
	if m != nil {
		return m.RequestFailureThreshold
	}
	return 0
}

func (m *SessionProxyConfig) GetMinimumRequestThreshold() uint32 {
	if m != nil {
		return m.MinimumRequestThreshold
	}
	return 0
}

type SwxConfig struct {
	LogLevel protos.LogLevel   `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	Server   *DiamClientConfig `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	// Flag to ensure that a user is authorized for Non-3GPP IP Access
	VerifyAuthorization bool   `protobuf:"varint,3,opt,name=verify_authorization,json=verifyAuthorization,proto3" json:"verify_authorization,omitempty"`
	CacheTTLSeconds     uint32 `protobuf:"varint,4,opt,name=CacheTTLSeconds,proto3" json:"CacheTTLSeconds,omitempty"`
	// Percentage of request failures considered to be unhealthy
	RequestFailureThreshold float32 `protobuf:"fixed32,5,opt,name=request_failure_threshold,json=requestFailureThreshold,proto3" json:"request_failure_threshold,omitempty"`
	// Minimum number of requests necessary to consider a metrics snapshot valid
	MinimumRequestThreshold uint32 `protobuf:"varint,6,opt,name=minimum_request_threshold,json=minimumRequestThreshold,proto3" json:"minimum_request_threshold,omitempty"`
	// Flag to ensure that we send SAR with REGISTER following successful MAA
	RegisterOnAuth bool `protobuf:"varint,7,opt,name=register_on_auth,json=registerOnAuth,proto3" json:"register_on_auth,omitempty"`
	// use returned maa.AAAServerName to derive Origin Realm from
	DeriveUnregisterRealm bool `protobuf:"varint,8,opt,name=derive_unregister_realm,json=deriveUnregisterRealm,proto3" json:"derive_unregister_realm,omitempty"`
	// PLMN IDs served by HLR
	HlrPlmnIds []string `protobuf:"bytes,9,rep,name=hlr_plmn_ids,json=hlrPlmnIds,proto3" json:"hlr_plmn_ids,omitempty"`
	// Server where SWx points to (can be one or more than one)
	Servers              []*DiamClientConfig `protobuf:"bytes,10,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SwxConfig) Reset()         { *m = SwxConfig{} }
func (m *SwxConfig) String() string { return proto.CompactTextString(m) }
func (*SwxConfig) ProtoMessage()    {}
func (*SwxConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{7}
}
func (m *SwxConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwxConfig.Unmarshal(m, b)
}
func (m *SwxConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwxConfig.Marshal(b, m, deterministic)
}
func (dst *SwxConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwxConfig.Merge(dst, src)
}
func (m *SwxConfig) XXX_Size() int {
	return xxx_messageInfo_SwxConfig.Size(m)
}
func (m *SwxConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SwxConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SwxConfig proto.InternalMessageInfo

func (m *SwxConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *SwxConfig) GetServer() *DiamClientConfig {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *SwxConfig) GetVerifyAuthorization() bool {
	if m != nil {
		return m.VerifyAuthorization
	}
	return false
}

func (m *SwxConfig) GetCacheTTLSeconds() uint32 {
	if m != nil {
		return m.CacheTTLSeconds
	}
	return 0
}

func (m *SwxConfig) GetRequestFailureThreshold() float32 {
	if m != nil {
		return m.RequestFailureThreshold
	}
	return 0
}

func (m *SwxConfig) GetMinimumRequestThreshold() uint32 {
	if m != nil {
		return m.MinimumRequestThreshold
	}
	return 0
}

func (m *SwxConfig) GetRegisterOnAuth() bool {
	if m != nil {
		return m.RegisterOnAuth
	}
	return false
}

func (m *SwxConfig) GetDeriveUnregisterRealm() bool {
	if m != nil {
		return m.DeriveUnregisterRealm
	}
	return false
}

func (m *SwxConfig) GetHlrPlmnIds() []string {
	if m != nil {
		return m.HlrPlmnIds
	}
	return nil
}

func (m *SwxConfig) GetServers() []*DiamClientConfig {
	if m != nil {
		return m.Servers
	}
	return nil
}

type EapAkaConfig struct {
	LogLevel             protos.LogLevel        `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	Timeout              *EapAkaConfig_Timeouts `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	PlmnIds              []string               `protobuf:"bytes,3,rep,name=PlmnIds,proto3" json:"PlmnIds,omitempty"`
	UseS6A               bool                   `protobuf:"varint,4,opt,name=UseS6a,proto3" json:"UseS6a,omitempty"`
	MncLen               int32                  `protobuf:"varint,5,opt,name=MncLen,proto3" json:"MncLen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EapAkaConfig) Reset()         { *m = EapAkaConfig{} }
func (m *EapAkaConfig) String() string { return proto.CompactTextString(m) }
func (*EapAkaConfig) ProtoMessage()    {}
func (*EapAkaConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{8}
}
func (m *EapAkaConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EapAkaConfig.Unmarshal(m, b)
}
func (m *EapAkaConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EapAkaConfig.Marshal(b, m, deterministic)
}
func (dst *EapAkaConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EapAkaConfig.Merge(dst, src)
}
func (m *EapAkaConfig) XXX_Size() int {
	return xxx_messageInfo_EapAkaConfig.Size(m)
}
func (m *EapAkaConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EapAkaConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EapAkaConfig proto.InternalMessageInfo

func (m *EapAkaConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *EapAkaConfig) GetTimeout() *EapAkaConfig_Timeouts {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *EapAkaConfig) GetPlmnIds() []string {
	if m != nil {
		return m.PlmnIds
	}
	return nil
}

func (m *EapAkaConfig) GetUseS6A() bool {
	if m != nil {
		return m.UseS6A
	}
	return false
}

func (m *EapAkaConfig) GetMncLen() int32 {
	if m != nil {
		return m.MncLen
	}
	return 0
}

type EapAkaConfig_Timeouts struct {
	ChallengeMs            uint32   `protobuf:"varint,1,opt,name=ChallengeMs,proto3" json:"ChallengeMs,omitempty"`
	ErrorNotificationMs    uint32   `protobuf:"varint,2,opt,name=ErrorNotificationMs,proto3" json:"ErrorNotificationMs,omitempty"`
	SessionMs              uint32   `protobuf:"varint,3,opt,name=SessionMs,proto3" json:"SessionMs,omitempty"`
	SessionAuthenticatedMs uint32   `protobuf:"varint,4,opt,name=SessionAuthenticatedMs,proto3" json:"SessionAuthenticatedMs,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *EapAkaConfig_Timeouts) Reset()         { *m = EapAkaConfig_Timeouts{} }
func (m *EapAkaConfig_Timeouts) String() string { return proto.CompactTextString(m) }
func (*EapAkaConfig_Timeouts) ProtoMessage()    {}
func (*EapAkaConfig_Timeouts) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{8, 0}
}
func (m *EapAkaConfig_Timeouts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EapAkaConfig_Timeouts.Unmarshal(m, b)
}
func (m *EapAkaConfig_Timeouts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EapAkaConfig_Timeouts.Marshal(b, m, deterministic)
}
func (dst *EapAkaConfig_Timeouts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EapAkaConfig_Timeouts.Merge(dst, src)
}
func (m *EapAkaConfig_Timeouts) XXX_Size() int {
	return xxx_messageInfo_EapAkaConfig_Timeouts.Size(m)
}
func (m *EapAkaConfig_Timeouts) XXX_DiscardUnknown() {
	xxx_messageInfo_EapAkaConfig_Timeouts.DiscardUnknown(m)
}

var xxx_messageInfo_EapAkaConfig_Timeouts proto.InternalMessageInfo

func (m *EapAkaConfig_Timeouts) GetChallengeMs() uint32 {
	if m != nil {
		return m.ChallengeMs
	}
	return 0
}

func (m *EapAkaConfig_Timeouts) GetErrorNotificationMs() uint32 {
	if m != nil {
		return m.ErrorNotificationMs
	}
	return 0
}

func (m *EapAkaConfig_Timeouts) GetSessionMs() uint32 {
	if m != nil {
		return m.SessionMs
	}
	return 0
}

func (m *EapAkaConfig_Timeouts) GetSessionAuthenticatedMs() uint32 {
	if m != nil {
		return m.SessionAuthenticatedMs
	}
	return 0
}

// EapProviderTimeouts is a generic EAP provider timeout config for all new providers
// TODO: It should eventually replace EapAkaConfig as well, but due to the braking nature
//       of the switch farther planning is required
type EapProviderTimeouts struct {
	ChallengeMs            uint32   `protobuf:"varint,1,opt,name=ChallengeMs,proto3" json:"ChallengeMs,omitempty"`
	ErrorNotificationMs    uint32   `protobuf:"varint,2,opt,name=ErrorNotificationMs,proto3" json:"ErrorNotificationMs,omitempty"`
	SessionMs              uint32   `protobuf:"varint,3,opt,name=SessionMs,proto3" json:"SessionMs,omitempty"`
	SessionAuthenticatedMs uint32   `protobuf:"varint,4,opt,name=SessionAuthenticatedMs,proto3" json:"SessionAuthenticatedMs,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *EapProviderTimeouts) Reset()         { *m = EapProviderTimeouts{} }
func (m *EapProviderTimeouts) String() string { return proto.CompactTextString(m) }
func (*EapProviderTimeouts) ProtoMessage()    {}
func (*EapProviderTimeouts) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{9}
}
func (m *EapProviderTimeouts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EapProviderTimeouts.Unmarshal(m, b)
}
func (m *EapProviderTimeouts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EapProviderTimeouts.Marshal(b, m, deterministic)
}
func (dst *EapProviderTimeouts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EapProviderTimeouts.Merge(dst, src)
}
func (m *EapProviderTimeouts) XXX_Size() int {
	return xxx_messageInfo_EapProviderTimeouts.Size(m)
}
func (m *EapProviderTimeouts) XXX_DiscardUnknown() {
	xxx_messageInfo_EapProviderTimeouts.DiscardUnknown(m)
}

var xxx_messageInfo_EapProviderTimeouts proto.InternalMessageInfo

func (m *EapProviderTimeouts) GetChallengeMs() uint32 {
	if m != nil {
		return m.ChallengeMs
	}
	return 0
}

func (m *EapProviderTimeouts) GetErrorNotificationMs() uint32 {
	if m != nil {
		return m.ErrorNotificationMs
	}
	return 0
}

func (m *EapProviderTimeouts) GetSessionMs() uint32 {
	if m != nil {
		return m.SessionMs
	}
	return 0
}

func (m *EapProviderTimeouts) GetSessionAuthenticatedMs() uint32 {
	if m != nil {
		return m.SessionAuthenticatedMs
	}
	return 0
}

type EapSimConfig struct {
	LogLevel             protos.LogLevel      `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	Timeout              *EapProviderTimeouts `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	PlmnIds              []string             `protobuf:"bytes,3,rep,name=PlmnIds,proto3" json:"PlmnIds,omitempty"`
	UseS6A               bool                 `protobuf:"varint,4,opt,name=UseS6a,proto3" json:"UseS6a,omitempty"`
	MncLen               int32                `protobuf:"varint,5,opt,name=MncLen,proto3" json:"MncLen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EapSimConfig) Reset()         { *m = EapSimConfig{} }
func (m *EapSimConfig) String() string { return proto.CompactTextString(m) }
func (*EapSimConfig) ProtoMessage()    {}
func (*EapSimConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{10}
}
func (m *EapSimConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EapSimConfig.Unmarshal(m, b)
}
func (m *EapSimConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EapSimConfig.Marshal(b, m, deterministic)
}
func (dst *EapSimConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EapSimConfig.Merge(dst, src)
}
func (m *EapSimConfig) XXX_Size() int {
	return xxx_messageInfo_EapSimConfig.Size(m)
}
func (m *EapSimConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EapSimConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EapSimConfig proto.InternalMessageInfo

func (m *EapSimConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *EapSimConfig) GetTimeout() *EapProviderTimeouts {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *EapSimConfig) GetPlmnIds() []string {
	if m != nil {
		return m.PlmnIds
	}
	return nil
}

func (m *EapSimConfig) GetUseS6A() bool {
	if m != nil {
		return m.UseS6A
	}
	return false
}

func (m *EapSimConfig) GetMncLen() int32 {
	if m != nil {
		return m.MncLen
	}
	return 0
}

type AAAConfig struct {
	LogLevel protos.LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	// Idle session TTL
	IdleSessionTimeoutMs uint32 `protobuf:"varint,2,opt,name=IdleSessionTimeoutMs,proto3" json:"IdleSessionTimeoutMs,omitempty"`
	// enable accounting & maintain long term user sessions
	AccountingEnabled bool `protobuf:"varint,3,opt,name=AccountingEnabled,proto3" json:"AccountingEnabled,omitempty"`
	// Postpone Auth success until successful accounting CreateSession completion
	CreateSessionOnAuth bool `protobuf:"varint,4,opt,name=CreateSessionOnAuth,proto3" json:"CreateSessionOnAuth,omitempty"`
	// enable event logging for aaa events
	EventLoggingEnabled  bool          `protobuf:"varint,5,opt,name=EventLoggingEnabled,proto3" json:"EventLoggingEnabled,omitempty"`
	RadiusConfig         *RadiusConfig `protobuf:"bytes,6,opt,name=RadiusConfig,proto3" json:"RadiusConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AAAConfig) Reset()         { *m = AAAConfig{} }
func (m *AAAConfig) String() string { return proto.CompactTextString(m) }
func (*AAAConfig) ProtoMessage()    {}
func (*AAAConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{11}
}
func (m *AAAConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AAAConfig.Unmarshal(m, b)
}
func (m *AAAConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AAAConfig.Marshal(b, m, deterministic)
}
func (dst *AAAConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AAAConfig.Merge(dst, src)
}
func (m *AAAConfig) XXX_Size() int {
	return xxx_messageInfo_AAAConfig.Size(m)
}
func (m *AAAConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AAAConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AAAConfig proto.InternalMessageInfo

func (m *AAAConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *AAAConfig) GetIdleSessionTimeoutMs() uint32 {
	if m != nil {
		return m.IdleSessionTimeoutMs
	}
	return 0
}

func (m *AAAConfig) GetAccountingEnabled() bool {
	if m != nil {
		return m.AccountingEnabled
	}
	return false
}

func (m *AAAConfig) GetCreateSessionOnAuth() bool {
	if m != nil {
		return m.CreateSessionOnAuth
	}
	return false
}

func (m *AAAConfig) GetEventLoggingEnabled() bool {
	if m != nil {
		return m.EventLoggingEnabled
	}
	return false
}

func (m *AAAConfig) GetRadiusConfig() *RadiusConfig {
	if m != nil {
		return m.RadiusConfig
	}
	return nil
}

type RadiusConfig struct {
	// Radius server secret
	Secret []byte `protobuf:"bytes,1,opt,name=Secret,proto3" json:"Secret,omitempty"`
	// Radius server network (udp/tcp/etc.
	Network string `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
	// Authentication Radius server address
	AuthAddr string `protobuf:"bytes,3,opt,name=AuthAddr,proto3" json:"AuthAddr,omitempty"`
	// Accounting Radius server address
	AcctAddr string `protobuf:"bytes,4,opt,name=AcctAddr,proto3" json:"AcctAddr,omitempty"`
	// DAE server Address
	DAEAddr              string   `protobuf:"bytes,5,opt,name=DAEAddr,proto3" json:"DAEAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RadiusConfig) Reset()         { *m = RadiusConfig{} }
func (m *RadiusConfig) String() string { return proto.CompactTextString(m) }
func (*RadiusConfig) ProtoMessage()    {}
func (*RadiusConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{12}
}
func (m *RadiusConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadiusConfig.Unmarshal(m, b)
}
func (m *RadiusConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadiusConfig.Marshal(b, m, deterministic)
}
func (dst *RadiusConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadiusConfig.Merge(dst, src)
}
func (m *RadiusConfig) XXX_Size() int {
	return xxx_messageInfo_RadiusConfig.Size(m)
}
func (m *RadiusConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RadiusConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RadiusConfig proto.InternalMessageInfo

func (m *RadiusConfig) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *RadiusConfig) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *RadiusConfig) GetAuthAddr() string {
	if m != nil {
		return m.AuthAddr
	}
	return ""
}

func (m *RadiusConfig) GetAcctAddr() string {
	if m != nil {
		return m.AcctAddr
	}
	return ""
}

func (m *RadiusConfig) GetDAEAddr() string {
	if m != nil {
		return m.DAEAddr
	}
	return ""
}

type GatewayHealthConfig struct {
	RequiredServices          []string `protobuf:"bytes,1,rep,name=required_services,json=requiredServices,proto3" json:"required_services,omitempty"`
	UpdateIntervalSecs        uint32   `protobuf:"varint,2,opt,name=update_interval_secs,json=updateIntervalSecs,proto3" json:"update_interval_secs,omitempty"`
	UpdateFailureThreshold    uint32   `protobuf:"varint,3,opt,name=update_failure_threshold,json=updateFailureThreshold,proto3" json:"update_failure_threshold,omitempty"`
	CloudDisconnectPeriodSecs uint32   `protobuf:"varint,4,opt,name=cloud_disconnect_period_secs,json=cloudDisconnectPeriodSecs,proto3" json:"cloud_disconnect_period_secs,omitempty"`
	LocalDisconnectPeriodSecs uint32   `protobuf:"varint,5,opt,name=local_disconnect_period_secs,json=localDisconnectPeriodSecs,proto3" json:"local_disconnect_period_secs,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *GatewayHealthConfig) Reset()         { *m = GatewayHealthConfig{} }
func (m *GatewayHealthConfig) String() string { return proto.CompactTextString(m) }
func (*GatewayHealthConfig) ProtoMessage()    {}
func (*GatewayHealthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{13}
}
func (m *GatewayHealthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayHealthConfig.Unmarshal(m, b)
}
func (m *GatewayHealthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayHealthConfig.Marshal(b, m, deterministic)
}
func (dst *GatewayHealthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayHealthConfig.Merge(dst, src)
}
func (m *GatewayHealthConfig) XXX_Size() int {
	return xxx_messageInfo_GatewayHealthConfig.Size(m)
}
func (m *GatewayHealthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayHealthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayHealthConfig proto.InternalMessageInfo

func (m *GatewayHealthConfig) GetRequiredServices() []string {
	if m != nil {
		return m.RequiredServices
	}
	return nil
}

func (m *GatewayHealthConfig) GetUpdateIntervalSecs() uint32 {
	if m != nil {
		return m.UpdateIntervalSecs
	}
	return 0
}

func (m *GatewayHealthConfig) GetUpdateFailureThreshold() uint32 {
	if m != nil {
		return m.UpdateFailureThreshold
	}
	return 0
}

func (m *GatewayHealthConfig) GetCloudDisconnectPeriodSecs() uint32 {
	if m != nil {
		return m.CloudDisconnectPeriodSecs
	}
	return 0
}

func (m *GatewayHealthConfig) GetLocalDisconnectPeriodSecs() uint32 {
	if m != nil {
		return m.LocalDisconnectPeriodSecs
	}
	return 0
}

type HSSConfig struct {
	Server *DiamServerConfig `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Operator configuration field for LTE.
	LteAuthOp []byte `protobuf:"bytes,2,opt,name=lte_auth_op,json=lteAuthOp,proto3" json:"lte_auth_op,omitempty"`
	// Authentication management field for LTE.
	LteAuthAmf []byte `protobuf:"bytes,3,opt,name=lte_auth_amf,json=lteAuthAmf,proto3" json:"lte_auth_amf,omitempty"`
	// Maps from IMSI to SubscriptionProfile.
	SubProfiles map[string]*HSSConfig_SubscriptionProfile `protobuf:"bytes,4,rep,name=sub_profiles,json=subProfiles,proto3" json:"sub_profiles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// If an IMSI if not found in sub_profiles, the default profile is used instead.
	DefaultSubProfile *HSSConfig_SubscriptionProfile `protobuf:"bytes,5,opt,name=default_sub_profile,json=defaultSubProfile,proto3" json:"default_sub_profile,omitempty"`
	// Whether to stream subscribers from the cloud subscriberdb service.
	StreamSubscribers    bool     `protobuf:"varint,6,opt,name=stream_subscribers,json=streamSubscribers,proto3" json:"stream_subscribers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HSSConfig) Reset()         { *m = HSSConfig{} }
func (m *HSSConfig) String() string { return proto.CompactTextString(m) }
func (*HSSConfig) ProtoMessage()    {}
func (*HSSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{14}
}
func (m *HSSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HSSConfig.Unmarshal(m, b)
}
func (m *HSSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HSSConfig.Marshal(b, m, deterministic)
}
func (dst *HSSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HSSConfig.Merge(dst, src)
}
func (m *HSSConfig) XXX_Size() int {
	return xxx_messageInfo_HSSConfig.Size(m)
}
func (m *HSSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HSSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HSSConfig proto.InternalMessageInfo

func (m *HSSConfig) GetServer() *DiamServerConfig {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *HSSConfig) GetLteAuthOp() []byte {
	if m != nil {
		return m.LteAuthOp
	}
	return nil
}

func (m *HSSConfig) GetLteAuthAmf() []byte {
	if m != nil {
		return m.LteAuthAmf
	}
	return nil
}

func (m *HSSConfig) GetSubProfiles() map[string]*HSSConfig_SubscriptionProfile {
	if m != nil {
		return m.SubProfiles
	}
	return nil
}

func (m *HSSConfig) GetDefaultSubProfile() *HSSConfig_SubscriptionProfile {
	if m != nil {
		return m.DefaultSubProfile
	}
	return nil
}

func (m *HSSConfig) GetStreamSubscribers() bool {
	if m != nil {
		return m.StreamSubscribers
	}
	return false
}

type HSSConfig_SubscriptionProfile struct {
	// Maximum uplink bit rate (AMBR-UL)
	MaxUlBitRate uint64 `protobuf:"varint,1,opt,name=max_ul_bit_rate,json=maxUlBitRate,proto3" json:"max_ul_bit_rate,omitempty"`
	// Maximum downlink bit rate (AMBR-DL)
	MaxDlBitRate         uint64   `protobuf:"varint,2,opt,name=max_dl_bit_rate,json=maxDlBitRate,proto3" json:"max_dl_bit_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HSSConfig_SubscriptionProfile) Reset()         { *m = HSSConfig_SubscriptionProfile{} }
func (m *HSSConfig_SubscriptionProfile) String() string { return proto.CompactTextString(m) }
func (*HSSConfig_SubscriptionProfile) ProtoMessage()    {}
func (*HSSConfig_SubscriptionProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{14, 0}
}
func (m *HSSConfig_SubscriptionProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HSSConfig_SubscriptionProfile.Unmarshal(m, b)
}
func (m *HSSConfig_SubscriptionProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HSSConfig_SubscriptionProfile.Marshal(b, m, deterministic)
}
func (dst *HSSConfig_SubscriptionProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HSSConfig_SubscriptionProfile.Merge(dst, src)
}
func (m *HSSConfig_SubscriptionProfile) XXX_Size() int {
	return xxx_messageInfo_HSSConfig_SubscriptionProfile.Size(m)
}
func (m *HSSConfig_SubscriptionProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_HSSConfig_SubscriptionProfile.DiscardUnknown(m)
}

var xxx_messageInfo_HSSConfig_SubscriptionProfile proto.InternalMessageInfo

func (m *HSSConfig_SubscriptionProfile) GetMaxUlBitRate() uint64 {
	if m != nil {
		return m.MaxUlBitRate
	}
	return 0
}

func (m *HSSConfig_SubscriptionProfile) GetMaxDlBitRate() uint64 {
	if m != nil {
		return m.MaxDlBitRate
	}
	return 0
}

type RadiusdConfig struct {
	// Port the metrics server is running on
	RadiusMetricsPort uint32 `protobuf:"varint,1,opt,name=radius_metrics_port,json=radiusMetricsPort,proto3" json:"radius_metrics_port,omitempty"`
	// The path to access the prometheus metrics on the server
	RadiusMetricsPath string `protobuf:"bytes,2,opt,name=radius_metrics_path,json=radiusMetricsPath,proto3" json:"radius_metrics_path,omitempty"`
	// Interval in seconds between fetching and updating metrics
	UpdateIntervalSecs uint32 `protobuf:"varint,3,opt,name=update_interval_secs,json=updateIntervalSecs,proto3" json:"update_interval_secs,omitempty"`
	// Hostname for prometheus metrics
	RadiusMetricsHost    string   `protobuf:"bytes,4,opt,name=radius_metrics_host,json=radiusMetricsHost,proto3" json:"radius_metrics_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RadiusdConfig) Reset()         { *m = RadiusdConfig{} }
func (m *RadiusdConfig) String() string { return proto.CompactTextString(m) }
func (*RadiusdConfig) ProtoMessage()    {}
func (*RadiusdConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{15}
}
func (m *RadiusdConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadiusdConfig.Unmarshal(m, b)
}
func (m *RadiusdConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadiusdConfig.Marshal(b, m, deterministic)
}
func (dst *RadiusdConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadiusdConfig.Merge(dst, src)
}
func (m *RadiusdConfig) XXX_Size() int {
	return xxx_messageInfo_RadiusdConfig.Size(m)
}
func (m *RadiusdConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RadiusdConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RadiusdConfig proto.InternalMessageInfo

func (m *RadiusdConfig) GetRadiusMetricsPort() uint32 {
	if m != nil {
		return m.RadiusMetricsPort
	}
	return 0
}

func (m *RadiusdConfig) GetRadiusMetricsPath() string {
	if m != nil {
		return m.RadiusMetricsPath
	}
	return ""
}

func (m *RadiusdConfig) GetUpdateIntervalSecs() uint32 {
	if m != nil {
		return m.UpdateIntervalSecs
	}
	return 0
}

func (m *RadiusdConfig) GetRadiusMetricsHost() string {
	if m != nil {
		return m.RadiusMetricsHost
	}
	return ""
}

type SCTPClientConfig struct {
	ServerAddress        string   `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	LocalAddress         string   `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCTPClientConfig) Reset()         { *m = SCTPClientConfig{} }
func (m *SCTPClientConfig) String() string { return proto.CompactTextString(m) }
func (*SCTPClientConfig) ProtoMessage()    {}
func (*SCTPClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{16}
}
func (m *SCTPClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCTPClientConfig.Unmarshal(m, b)
}
func (m *SCTPClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCTPClientConfig.Marshal(b, m, deterministic)
}
func (dst *SCTPClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCTPClientConfig.Merge(dst, src)
}
func (m *SCTPClientConfig) XXX_Size() int {
	return xxx_messageInfo_SCTPClientConfig.Size(m)
}
func (m *SCTPClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SCTPClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SCTPClientConfig proto.InternalMessageInfo

func (m *SCTPClientConfig) GetServerAddress() string {
	if m != nil {
		return m.ServerAddress
	}
	return ""
}

func (m *SCTPClientConfig) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

type CsfbConfig struct {
	LogLevel             protos.LogLevel   `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	Client               *SCTPClientConfig `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CsfbConfig) Reset()         { *m = CsfbConfig{} }
func (m *CsfbConfig) String() string { return proto.CompactTextString(m) }
func (*CsfbConfig) ProtoMessage()    {}
func (*CsfbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{17}
}
func (m *CsfbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CsfbConfig.Unmarshal(m, b)
}
func (m *CsfbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CsfbConfig.Marshal(b, m, deterministic)
}
func (dst *CsfbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CsfbConfig.Merge(dst, src)
}
func (m *CsfbConfig) XXX_Size() int {
	return xxx_messageInfo_CsfbConfig.Size(m)
}
func (m *CsfbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CsfbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CsfbConfig proto.InternalMessageInfo

func (m *CsfbConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *CsfbConfig) GetClient() *SCTPClientConfig {
	if m != nil {
		return m.Client
	}
	return nil
}

type EnvoyControllerConfig struct {
	LogLevel             protos.LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EnvoyControllerConfig) Reset()         { *m = EnvoyControllerConfig{} }
func (m *EnvoyControllerConfig) String() string { return proto.CompactTextString(m) }
func (*EnvoyControllerConfig) ProtoMessage()    {}
func (*EnvoyControllerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{18}
}
func (m *EnvoyControllerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoyControllerConfig.Unmarshal(m, b)
}
func (m *EnvoyControllerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoyControllerConfig.Marshal(b, m, deterministic)
}
func (dst *EnvoyControllerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoyControllerConfig.Merge(dst, src)
}
func (m *EnvoyControllerConfig) XXX_Size() int {
	return xxx_messageInfo_EnvoyControllerConfig.Size(m)
}
func (m *EnvoyControllerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoyControllerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoyControllerConfig proto.InternalMessageInfo

func (m *EnvoyControllerConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

type S8Config struct {
	LogLevel             protos.LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	LocalAddress         string          `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	PgwAddress           string          `protobuf:"bytes,3,opt,name=pgw_address,json=pgwAddress,proto3" json:"pgw_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *S8Config) Reset()         { *m = S8Config{} }
func (m *S8Config) String() string { return proto.CompactTextString(m) }
func (*S8Config) ProtoMessage()    {}
func (*S8Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{19}
}
func (m *S8Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S8Config.Unmarshal(m, b)
}
func (m *S8Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S8Config.Marshal(b, m, deterministic)
}
func (dst *S8Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S8Config.Merge(dst, src)
}
func (m *S8Config) XXX_Size() int {
	return xxx_messageInfo_S8Config.Size(m)
}
func (m *S8Config) XXX_DiscardUnknown() {
	xxx_messageInfo_S8Config.DiscardUnknown(m)
}

var xxx_messageInfo_S8Config proto.InternalMessageInfo

func (m *S8Config) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *S8Config) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *S8Config) GetPgwAddress() string {
	if m != nil {
		return m.PgwAddress
	}
	return ""
}

type RadiusProxyConfig struct {
	LogLevel             protos.LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=magma.orc8r.LogLevel" json:"log_level,omitempty"`
	LocalAddress         string          `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	AaaAddress           string          `protobuf:"bytes,3,opt,name=aaa_address,json=aaaAddress,proto3" json:"aaa_address,omitempty"`
	ServerSecret         string          `protobuf:"bytes,4,opt,name=server_secret,json=serverSecret,proto3" json:"server_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RadiusProxyConfig) Reset()         { *m = RadiusProxyConfig{} }
func (m *RadiusProxyConfig) String() string { return proto.CompactTextString(m) }
func (*RadiusProxyConfig) ProtoMessage()    {}
func (*RadiusProxyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mconfigs_15c9a07543a15489, []int{20}
}
func (m *RadiusProxyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadiusProxyConfig.Unmarshal(m, b)
}
func (m *RadiusProxyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadiusProxyConfig.Marshal(b, m, deterministic)
}
func (dst *RadiusProxyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadiusProxyConfig.Merge(dst, src)
}
func (m *RadiusProxyConfig) XXX_Size() int {
	return xxx_messageInfo_RadiusProxyConfig.Size(m)
}
func (m *RadiusProxyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RadiusProxyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RadiusProxyConfig proto.InternalMessageInfo

func (m *RadiusProxyConfig) GetLogLevel() protos.LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return protos.LogLevel_DEBUG
}

func (m *RadiusProxyConfig) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *RadiusProxyConfig) GetAaaAddress() string {
	if m != nil {
		return m.AaaAddress
	}
	return ""
}

func (m *RadiusProxyConfig) GetServerSecret() string {
	if m != nil {
		return m.ServerSecret
	}
	return ""
}

func init() {
	proto.RegisterType((*DiamClientConfig)(nil), "magma.mconfig.DiamClientConfig")
	proto.RegisterType((*DiamServerConfig)(nil), "magma.mconfig.DiamServerConfig")
	proto.RegisterType((*S6AConfig)(nil), "magma.mconfig.S6aConfig")
	proto.RegisterType((*VirtualApnRule)(nil), "magma.mconfig.VirtualApnRule")
	proto.RegisterType((*GxConfig)(nil), "magma.mconfig.GxConfig")
	proto.RegisterType((*GyConfig)(nil), "magma.mconfig.GyConfig")
	proto.RegisterType((*SessionProxyConfig)(nil), "magma.mconfig.SessionProxyConfig")
	proto.RegisterType((*SwxConfig)(nil), "magma.mconfig.SwxConfig")
	proto.RegisterType((*EapAkaConfig)(nil), "magma.mconfig.EapAkaConfig")
	proto.RegisterType((*EapAkaConfig_Timeouts)(nil), "magma.mconfig.EapAkaConfig.Timeouts")
	proto.RegisterType((*EapProviderTimeouts)(nil), "magma.mconfig.EapProviderTimeouts")
	proto.RegisterType((*EapSimConfig)(nil), "magma.mconfig.EapSimConfig")
	proto.RegisterType((*AAAConfig)(nil), "magma.mconfig.AAAConfig")
	proto.RegisterType((*RadiusConfig)(nil), "magma.mconfig.RadiusConfig")
	proto.RegisterType((*GatewayHealthConfig)(nil), "magma.mconfig.GatewayHealthConfig")
	proto.RegisterType((*HSSConfig)(nil), "magma.mconfig.HSSConfig")
	proto.RegisterMapType((map[string]*HSSConfig_SubscriptionProfile)(nil), "magma.mconfig.HSSConfig.SubProfilesEntry")
	proto.RegisterType((*HSSConfig_SubscriptionProfile)(nil), "magma.mconfig.HSSConfig.SubscriptionProfile")
	proto.RegisterType((*RadiusdConfig)(nil), "magma.mconfig.RadiusdConfig")
	proto.RegisterType((*SCTPClientConfig)(nil), "magma.mconfig.SCTPClientConfig")
	proto.RegisterType((*CsfbConfig)(nil), "magma.mconfig.CsfbConfig")
	proto.RegisterType((*EnvoyControllerConfig)(nil), "magma.mconfig.EnvoyControllerConfig")
	proto.RegisterType((*S8Config)(nil), "magma.mconfig.S8Config")
	proto.RegisterType((*RadiusProxyConfig)(nil), "magma.mconfig.RadiusProxyConfig")
	proto.RegisterEnum("magma.mconfig.GyInitMethod", GyInitMethod_name, GyInitMethod_value)
}

func init() {
	proto.RegisterFile("feg/protos/mconfig/mconfigs.proto", fileDescriptor_mconfigs_15c9a07543a15489)
}

var fileDescriptor_mconfigs_15c9a07543a15489 = []byte{
	// 1852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcd, 0x6f, 0x1b, 0xb9,
	0x15, 0xaf, 0x24, 0x7f, 0x48, 0x4f, 0xb2, 0x2d, 0xd3, 0xf9, 0x50, 0xbc, 0x49, 0xe3, 0xcc, 0x76,
	0x51, 0x77, 0x77, 0x2b, 0x6f, 0x5d, 0x20, 0x4d, 0x83, 0x45, 0x03, 0x45, 0x56, 0x12, 0x63, 0xed,
	0xc4, 0x98, 0x71, 0x16, 0x68, 0x51, 0x74, 0x40, 0xcf, 0x50, 0x23, 0x22, 0x33, 0xc3, 0x29, 0x87,
	0x23, 0x5b, 0xbd, 0xb6, 0xa7, 0xb6, 0xa7, 0x3d, 0xf7, 0x1f, 0xe8, 0xad, 0x28, 0xf6, 0x5e, 0xa0,
	0x87, 0x02, 0xed, 0xad, 0xff, 0x51, 0xc1, 0x8f, 0x19, 0x7d, 0x58, 0x36, 0xe2, 0xa8, 0x3d, 0xf4,
	0x24, 0xf1, 0xfd, 0x7e, 0x24, 0x1f, 0x7f, 0x7c, 0x7c, 0xe4, 0x1b, 0x78, 0xd4, 0x27, 0xc1, 0x5e,
	0xc2, 0x99, 0x60, 0xe9, 0x5e, 0xe4, 0xb1, 0xb8, 0x4f, 0x83, 0xfc, 0x37, 0x6d, 0x2b, 0x3b, 0x5a,
	0x8b, 0x70, 0x10, 0xe1, 0xb6, 0xb1, 0x6e, 0xdf, 0x63, 0xdc, 0x7b, 0xc2, 0xf3, 0x3e, 0x1e, 0x8b,
	0x22, 0x16, 0x6b, 0xa6, 0xf5, 0xf7, 0x0a, 0x34, 0x0f, 0x28, 0x8e, 0xba, 0x21, 0x25, 0xb1, 0xe8,
	0x2a, 0x3e, 0xda, 0x86, 0xaa, 0x42, 0x3d, 0x16, 0xb6, 0x4a, 0x3b, 0xa5, 0xdd, 0x9a, 0x5d, 0xb4,
	0x51, 0x0b, 0x56, 0xb1, 0xef, 0x73, 0x92, 0xa6, 0xad, 0xb2, 0x82, 0xf2, 0x26, 0xda, 0x81, 0x3a,
	0x27, 0x82, 0xe3, 0x38, 0x8d, 0xa8, 0x48, 0x5b, 0x95, 0x9d, 0xd2, 0xee, 0x9a, 0x3d, 0x69, 0x42,
	0x9f, 0xc1, 0xe6, 0x39, 0x16, 0xde, 0xc0, 0x67, 0x81, 0x4b, 0x63, 0x41, 0xf8, 0x10, 0x87, 0xad,
	0x25, 0xc5, 0x6b, 0xe6, 0xc0, 0xa1, 0xb1, 0xa3, 0x87, 0x7a, 0xb8, 0x91, 0xeb, 0xb1, 0x2c, 0x16,
	0xad, 0x65, 0x45, 0x03, 0x65, 0xea, 0x4a, 0x0b, 0xfa, 0x18, 0xd6, 0x42, 0xe6, 0xe1, 0xd0, 0xcd,
	0xfd, 0x59, 0x51, 0xfe, 0x34, 0x94, 0xb1, 0x63, 0x9c, 0x7a, 0x04, 0x8d, 0x84, 0x33, 0x3f, 0xf3,
	0x84, 0x1b, 0xe3, 0x88, 0xb4, 0x56, 0x15, 0xa7, 0x6e, 0x6c, 0xaf, 0x71, 0x44, 0xd0, 0x2d, 0x58,
	0xe6, 0x04, 0x87, 0x51, 0xab, 0xaa, 0x30, 0xdd, 0x40, 0x08, 0x96, 0x06, 0x2c, 0x15, 0xad, 0x9a,
	0x32, 0xaa, 0xff, 0xe8, 0x01, 0x80, 0x4f, 0x52, 0xe1, 0x6a, 0x3a, 0x28, 0xa4, 0x26, 0x2d, 0xb6,
	0xea, 0xf2, 0x11, 0xa8, 0x86, 0xab, 0xfa, 0xd5, 0xb5, 0x6e, 0xd2, 0xf0, 0x4a, 0xf6, 0xfd, 0x14,
	0x36, 0x7d, 0x9a, 0xe2, 0xb3, 0x90, 0xb8, 0x63, 0x52, 0x63, 0xa7, 0xb4, 0x5b, 0xb5, 0x37, 0x0c,
	0x70, 0x90, 0x73, 0xdb, 0xb0, 0xc5, 0x86, 0x84, 0x9f, 0x73, 0x2a, 0x26, 0xd9, 0x6b, 0x8a, 0xbd,
	0x59, 0x40, 0x39, 0xdf, 0xfa, 0x73, 0x49, 0x6f, 0xa2, 0x43, 0xf8, 0x90, 0xf0, 0x85, 0x36, 0xf1,
	0x92, 0xa8, 0x95, 0x39, 0xa2, 0x4e, 0x2d, 0x74, 0x69, 0x66, 0xa1, 0xd3, 0x22, 0x2d, 0xcf, 0x88,
	0x64, 0xfd, 0xbe, 0x0c, 0x35, 0xe7, 0x31, 0x36, 0x4e, 0xee, 0x43, 0x2d, 0x64, 0x81, 0x1b, 0x92,
	0x21, 0xd1, 0x5e, 0xae, 0xef, 0xdf, 0x6e, 0xeb, 0xe0, 0x55, 0x31, 0xdb, 0x3e, 0x62, 0xc1, 0x91,
	0x04, 0xed, 0x6a, 0x68, 0xfe, 0xa1, 0x9f, 0xc0, 0x4a, 0xaa, 0x16, 0xaa, 0x06, 0xaf, 0xef, 0x3f,
	0x6c, 0x4f, 0x45, 0x7b, 0x7b, 0x36, 0x9c, 0x6d, 0x43, 0x47, 0x4f, 0xe1, 0x1e, 0x27, 0xbf, 0xce,
	0xa4, 0x73, 0x7d, 0x4c, 0xc3, 0x8c, 0x13, 0x57, 0x0c, 0x38, 0x49, 0x07, 0x2c, 0xf4, 0x55, 0xf0,
	0x94, 0xed, 0xbb, 0x86, 0xf0, 0x42, 0xe3, 0xa7, 0x39, 0x2c, 0xfb, 0x46, 0x34, 0xa6, 0x51, 0x16,
	0xb9, 0xf9, 0x18, 0xe3, 0xbe, 0xab, 0x2a, 0x36, 0xef, 0x1a, 0x82, 0xad, 0xf1, 0x71, 0xdf, 0x16,
	0xac, 0x9e, 0x84, 0x51, 0x7c, 0xe8, 0xa7, 0xad, 0xea, 0x4e, 0x45, 0xaa, 0x6d, 0x9a, 0xd6, 0x9f,
	0x4a, 0xb0, 0xfe, 0x35, 0xe5, 0x22, 0xc3, 0x61, 0x27, 0x89, 0xed, 0x2c, 0x24, 0x52, 0x3e, 0x9c,
	0xc4, 0x6e, 0x9f, 0x86, 0x82, 0x70, 0xb3, 0x71, 0x35, 0x9c, 0xc4, 0x2f, 0x94, 0x41, 0xee, 0x8f,
	0x84, 0x8b, 0x18, 0x30, 0xfb, 0xd7, 0xc0, 0x49, 0xfc, 0x26, 0xb7, 0xa1, 0x17, 0xf0, 0xd0, 0x1b,
	0x60, 0x1e, 0xd0, 0x38, 0x70, 0xe5, 0x1f, 0xec, 0x09, 0xc2, 0x69, 0x2a, 0xa8, 0x97, 0xe6, 0x03,
	0xeb, 0x6d, 0x7d, 0x90, 0xd3, 0xba, 0xd3, 0x2c, 0x3d, 0x99, 0xf5, 0x87, 0x32, 0x54, 0x5f, 0x5e,
	0x98, 0xad, 0x1a, 0xcb, 0x5e, 0xba, 0x99, 0xec, 0x16, 0x34, 0x0a, 0xd7, 0x3a, 0x49, 0x9c, 0x7b,
	0x3c, 0x69, 0x43, 0x3f, 0x85, 0x55, 0xcd, 0x96, 0x01, 0x57, 0x79, 0x9f, 0xd1, 0x73, 0x3e, 0xba,
	0x0f, 0xb5, 0x03, 0x7d, 0x7e, 0x5e, 0x5e, 0xa8, 0x60, 0xac, 0xda, 0x63, 0x03, 0x3a, 0x84, 0xcd,
	0xa1, 0x16, 0xd8, 0x95, 0xba, 0xf1, 0x2c, 0x24, 0x69, 0x6b, 0x59, 0x4d, 0xf1, 0x60, 0x66, 0x8a,
	0xe9, 0x8d, 0xb0, 0x37, 0x86, 0x53, 0xed, 0xd4, 0xfa, 0xa7, 0x54, 0x63, 0xb4, 0xa8, 0x1a, 0x5f,
	0x42, 0x9d, 0xc6, 0x54, 0xb8, 0x11, 0x11, 0x03, 0xe6, 0x2b, 0x31, 0xd6, 0xf7, 0x3f, 0x9a, 0xe9,
	0xfd, 0x72, 0x74, 0x18, 0x53, 0x71, 0xac, 0x28, 0x36, 0xd0, 0xe2, 0xff, 0x25, 0x2d, 0x2b, 0xd7,
	0x6b, 0xb9, 0xf4, 0xe1, 0x5a, 0x8e, 0xd4, 0xe9, 0x9a, 0xd0, 0x72, 0x34, 0x5f, 0xcb, 0x95, 0x0f,
	0xd2, 0xf2, 0x9b, 0x32, 0x20, 0x87, 0xa4, 0x29, 0x65, 0xf1, 0x09, 0x67, 0x17, 0xa3, 0x05, 0xd2,
	0xc1, 0xf7, 0xa1, 0x1c, 0x5c, 0x98, 0x54, 0x70, 0x77, 0x56, 0x47, 0x13, 0xbc, 0x76, 0x39, 0xb8,
	0x50, 0xc4, 0x91, 0x3a, 0xe7, 0x73, 0x88, 0xa3, 0x82, 0x38, 0xba, 0x3e, 0x4f, 0xac, 0x2e, 0x90,
	0x27, 0xaa, 0xd7, 0xe6, 0x09, 0xeb, 0x8f, 0x4b, 0x50, 0x73, 0xce, 0x2f, 0xfe, 0x2b, 0xa9, 0xb1,
	0x7c, 0xb3, 0xa8, 0xfc, 0x11, 0xdc, 0x1a, 0x12, 0x4e, 0xfb, 0x23, 0x17, 0x67, 0x62, 0xc0, 0x38,
	0xfd, 0x0d, 0x16, 0x94, 0xe9, 0xf8, 0xaa, 0xda, 0x5b, 0x1a, 0xeb, 0x4c, 0x42, 0x68, 0x17, 0x36,
	0xba, 0xd8, 0x1b, 0x90, 0xd3, 0xd3, 0x23, 0x87, 0x78, 0x2c, 0xf6, 0x53, 0x73, 0x95, 0xcf, 0x9a,
	0xaf, 0xd7, 0x73, 0x79, 0x01, 0x3d, 0x57, 0xae, 0xcf, 0xbb, 0xbb, 0xd0, 0xe4, 0x24, 0xa0, 0xa9,
	0x20, 0xdc, 0x65, 0xb1, 0x5a, 0x99, 0xda, 0xbe, 0xaa, 0xbd, 0x9e, 0xdb, 0xdf, 0xc4, 0x72, 0x51,
	0xe8, 0x31, 0xdc, 0xf5, 0x09, 0xa7, 0x43, 0xe2, 0x66, 0x71, 0xd1, 0x65, 0xfc, 0x28, 0xa8, 0xda,
	0xb7, 0x35, 0xfc, 0xb6, 0x40, 0xf5, 0x8d, 0xbf, 0x03, 0x8d, 0x41, 0xc8, 0xdd, 0x24, 0x8c, 0x62,
	0x97, 0xfa, 0x69, 0xab, 0xa6, 0xd2, 0x3b, 0x0c, 0x42, 0x6e, 0x32, 0xfc, 0xe4, 0x61, 0x84, 0x9b,
	0x1d, 0x46, 0xeb, 0xb7, 0x15, 0x68, 0xf4, 0x70, 0xd2, 0x79, 0xb7, 0xc8, 0x65, 0xf9, 0x33, 0x58,
	0x15, 0x34, 0x22, 0x2c, 0x13, 0x26, 0x24, 0xbe, 0x37, 0x33, 0xff, 0xe4, 0x0c, 0xed, 0x53, 0x4d,
	0x4d, 0xed, 0xbc, 0xd3, 0xe4, 0xdd, 0x55, 0x99, 0xba, 0xbb, 0xd0, 0x1d, 0x58, 0x79, 0x9b, 0x12,
	0xe7, 0x31, 0x36, 0x49, 0xd7, 0xb4, 0xa4, 0xfd, 0x38, 0xf6, 0x8e, 0x48, 0xac, 0xb6, 0x76, 0xd9,
	0x36, 0xad, 0xed, 0x6f, 0x4b, 0x50, 0xcd, 0xc7, 0x97, 0x6f, 0xc5, 0xee, 0x00, 0x87, 0x21, 0x89,
	0x03, 0x72, 0x9c, 0xaa, 0xc5, 0xac, 0xd9, 0x93, 0x26, 0xf4, 0x05, 0x6c, 0xf5, 0x38, 0x67, 0xfc,
	0x35, 0x13, 0xb4, 0x4f, 0x3d, 0x15, 0x73, 0xc7, 0xfa, 0xb9, 0xb2, 0x66, 0xcf, 0x83, 0x64, 0xf2,
	0x32, 0x29, 0xe5, 0x38, 0x7f, 0x7d, 0x8e, 0x0d, 0xe8, 0x31, 0xdc, 0x31, 0x0d, 0xb9, 0xe3, 0x24,
	0x16, 0xb2, 0x23, 0xf1, 0x8f, 0xf3, 0xa8, 0xbd, 0x02, 0xb5, 0xfe, 0x56, 0x82, 0xad, 0x1e, 0x4e,
	0x4e, 0x38, 0x1b, 0x52, 0x9f, 0xf0, 0xff, 0xc3, 0x15, 0xfc, 0xab, 0xa4, 0xe2, 0xc8, 0xa1, 0xd1,
	0x02, 0x71, 0xf4, 0xe5, 0x6c, 0x1c, 0x59, 0x97, 0xe3, 0x68, 0x56, 0xa3, 0xff, 0x41, 0x14, 0x59,
	0xff, 0x28, 0x43, 0xad, 0xd3, 0xe9, 0x2c, 0xb0, 0x92, 0x7d, 0xb8, 0x75, 0xe8, 0x87, 0xc4, 0x88,
	0x65, 0x7c, 0x2d, 0xf6, 0x65, 0x2e, 0x86, 0x3e, 0x87, 0xcd, 0x8e, 0xa7, 0xea, 0x10, 0x1a, 0x07,
	0xbd, 0x58, 0xde, 0x87, 0xbe, 0xc9, 0x8d, 0x97, 0x01, 0xb9, 0xf1, 0x5d, 0x4e, 0xb0, 0xc8, 0xc7,
	0xd1, 0x49, 0xc6, 0x2c, 0x70, 0x1e, 0xa4, 0x42, 0x65, 0x48, 0x62, 0x71, 0xc4, 0x82, 0x60, 0x62,
	0x06, 0x7d, 0x03, 0xcf, 0x83, 0xd0, 0x33, 0x68, 0xd8, 0xd8, 0xa7, 0x59, 0xaa, 0x95, 0x30, 0xd7,
	0xda, 0xec, 0x3b, 0x62, 0x92, 0x62, 0x4f, 0x75, 0xb0, 0xbe, 0x29, 0x4d, 0x8f, 0x20, 0x15, 0x77,
	0x88, 0xc7, 0x89, 0x50, 0x42, 0x36, 0x6c, 0xd3, 0x92, 0x7b, 0xf7, 0x9a, 0x88, 0x73, 0xc6, 0xdf,
	0xe5, 0xb5, 0x82, 0x69, 0xca, 0x0a, 0x43, 0x7a, 0x2f, 0xab, 0x02, 0xf3, 0x10, 0x29, 0xda, 0x0a,
	0xf3, 0x3c, 0xa1, 0x30, 0x53, 0x21, 0xe4, 0x6d, 0x39, 0xe2, 0x41, 0xa7, 0xa7, 0x20, 0x5d, 0x1e,
	0xe4, 0x4d, 0xeb, 0x2f, 0x65, 0xd8, 0x7a, 0x89, 0x05, 0x39, 0xc7, 0xa3, 0x57, 0x04, 0x87, 0x62,
	0x60, 0x7c, 0xfb, 0x0c, 0x36, 0x65, 0xf6, 0xa7, 0x9c, 0xf8, 0xae, 0x4c, 0x8f, 0xd4, 0x23, 0xf2,
	0xc8, 0xc9, 0x48, 0x6a, 0xe6, 0x80, 0x63, 0xec, 0xe8, 0x0b, 0xb8, 0x95, 0x25, 0x3e, 0x16, 0xa4,
	0xa8, 0x31, 0xdd, 0x94, 0x78, 0xf9, 0x06, 0x23, 0x8d, 0xe5, 0x65, 0xa6, 0x43, 0xbc, 0x14, 0x3d,
	0x81, 0x96, 0xe9, 0x71, 0xf9, 0x7e, 0xd2, 0xc7, 0xf0, 0x8e, 0xc6, 0x2f, 0x5d, 0x4f, 0xcf, 0xe0,
	0xbe, 0x17, 0xb2, 0xcc, 0x77, 0x7d, 0x9a, 0x7a, 0x2c, 0x8e, 0x89, 0x27, 0xdc, 0x84, 0x70, 0xca,
	0x7c, 0x3d, 0xa7, 0x3e, 0x99, 0xf7, 0x14, 0xe7, 0xa0, 0xa0, 0x9c, 0x28, 0x86, 0x9a, 0xfa, 0x19,
	0xdc, 0xd7, 0xf5, 0xd6, 0x15, 0x03, 0xe8, 0xb2, 0xf7, 0x9e, 0xe2, 0xcc, 0x1b, 0xc0, 0xfa, 0x76,
	0x09, 0x6a, 0xaf, 0x1c, 0xe7, 0x06, 0xcf, 0xd2, 0xc9, 0x2a, 0xb1, 0x78, 0x00, 0x7c, 0x17, 0xea,
	0xa1, 0x20, 0xea, 0x8e, 0x74, 0x59, 0xa2, 0xb4, 0x6a, 0xd8, 0xb5, 0x50, 0x10, 0xb9, 0xa3, 0x6f,
	0x12, 0x79, 0xd3, 0x15, 0x38, 0x8e, 0xfa, 0x4a, 0x96, 0x86, 0x0d, 0x86, 0xd0, 0x89, 0xfa, 0xe8,
	0x08, 0x1a, 0x69, 0x76, 0xe6, 0x26, 0x9c, 0xf5, 0xa9, 0x7c, 0x18, 0xea, 0xb7, 0xe7, 0x0f, 0x66,
	0x1c, 0x28, 0x5c, 0x6d, 0x3b, 0xd9, 0xd9, 0x89, 0xe1, 0xf6, 0x62, 0xc1, 0x47, 0x76, 0x3d, 0x1d,
	0x5b, 0xd0, 0x2f, 0x61, 0xcb, 0x27, 0x7d, 0x9c, 0x85, 0xc2, 0x9d, 0x18, 0xd5, 0x3c, 0xf3, 0x3e,
	0xbf, 0x6e, 0xd0, 0xd4, 0xe3, 0x34, 0x11, 0xfa, 0x61, 0x29, 0xfb, 0xd8, 0x9b, 0x66, 0xa0, 0xf1,
	0x84, 0xe8, 0x87, 0x80, 0x52, 0xc1, 0x09, 0x8e, 0xe4, 0xe0, 0xb2, 0xc3, 0x99, 0xbc, 0xa0, 0x57,
	0xf4, 0x81, 0xd6, 0x88, 0x33, 0x06, 0xb6, 0x3d, 0xd8, 0x9a, 0x33, 0x30, 0xfa, 0x04, 0x36, 0x22,
	0x7c, 0xe1, 0x66, 0xa1, 0x7b, 0x46, 0x85, 0xcb, 0xb1, 0x20, 0x4a, 0xf5, 0x25, 0xbb, 0x11, 0xe1,
	0x8b, 0xb7, 0xe1, 0x73, 0x2a, 0x6c, 0x2c, 0x0a, 0x9a, 0x3f, 0x41, 0x2b, 0x17, 0xb4, 0x83, 0x9c,
	0xb6, 0x1d, 0x42, 0x73, 0x56, 0x12, 0xd4, 0x84, 0xca, 0x3b, 0x32, 0x32, 0x55, 0xa0, 0xfc, 0x8b,
	0x9e, 0xc3, 0xf2, 0x10, 0x87, 0x19, 0x31, 0x59, 0xf8, 0x66, 0x4a, 0xe8, 0xae, 0x4f, 0xcb, 0x4f,
	0x4a, 0xd6, 0xbf, 0x4b, 0xb0, 0xa6, 0x8f, 0xbf, 0x6f, 0x42, 0xa7, 0x0d, 0x5b, 0x5c, 0x19, 0x64,
	0x69, 0xc2, 0x65, 0xa9, 0x98, 0x30, 0x2e, 0xcc, 0xc5, 0xb6, 0xa9, 0xa1, 0x63, 0x8d, 0x9c, 0x30,
	0x2e, 0xe6, 0xf1, 0xb1, 0x18, 0x98, 0x1c, 0x31, 0xc3, 0xc7, 0x2a, 0xc7, 0xcd, 0x3f, 0x96, 0x95,
	0x2b, 0x8f, 0xe5, 0xe5, 0x19, 0x26, 0x3e, 0x38, 0x4c, 0xcf, 0xa0, 0x3e, 0x83, 0xfc, 0x0a, 0x9a,
	0x4e, 0xf7, 0xf4, 0x64, 0xea, 0x53, 0xd6, 0x27, 0xb0, 0xae, 0x23, 0xbc, 0xf8, 0xa0, 0xa1, 0xc5,
	0x5c, 0xd3, 0xd6, 0xce, 0x55, 0x9f, 0x3d, 0xca, 0x97, 0x3f, 0x7b, 0x58, 0x23, 0x80, 0x6e, 0xda,
	0x3f, 0x5b, 0xec, 0x7d, 0xee, 0x29, 0xef, 0xae, 0x78, 0x9f, 0xcf, 0xba, 0x6f, 0x1b, 0xba, 0xf5,
	0x15, 0xdc, 0xee, 0xc5, 0x43, 0x26, 0xab, 0x14, 0xc1, 0x59, 0x18, 0x16, 0x5f, 0x79, 0x3e, 0xc0,
	0x0b, 0xeb, 0x77, 0x25, 0xa8, 0x3a, 0x4f, 0x16, 0x58, 0xc6, 0xfb, 0xa8, 0x85, 0x1e, 0x42, 0x3d,
	0x09, 0xce, 0x67, 0xbe, 0x23, 0x41, 0x12, 0x9c, 0xe7, 0x72, 0xfe, 0xb5, 0x04, 0x9b, 0x3a, 0x04,
	0x17, 0x2d, 0x01, 0xdf, 0xd7, 0x1f, 0x8c, 0xf1, 0xac, 0x3f, 0x18, 0xe3, 0x89, 0x18, 0x30, 0xa1,
	0x92, 0xea, 0x7b, 0x50, 0x07, 0x5a, 0x43, 0x1b, 0xf5, 0x6d, 0xf8, 0xe9, 0x53, 0x68, 0x4c, 0x16,
	0xe7, 0xa8, 0x01, 0x55, 0xbb, 0xe7, 0xf4, 0xec, 0xaf, 0x7b, 0x07, 0xcd, 0xef, 0xa0, 0x0d, 0xa8,
	0x9f, 0xf4, 0x6c, 0xd7, 0xe9, 0x39, 0xce, 0xe1, 0x9b, 0xd7, 0xcd, 0x12, 0xaa, 0xc3, 0xaa, 0x34,
	0x7c, 0xd5, 0xfb, 0x79, 0xb3, 0xfc, 0xfc, 0xe3, 0x5f, 0x3c, 0x52, 0x0b, 0xd9, 0xeb, 0x93, 0x60,
	0x4f, 0x5d, 0x09, 0x7b, 0x01, 0x9b, 0xf9, 0x92, 0x7b, 0xb6, 0xa2, 0xda, 0x3f, 0xfe, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x45, 0xfd, 0xaa, 0x2e, 0xe6, 0x15, 0x00, 0x00,
}
